defaults:
  - _self_
  - dataset: cedr
  - model: rubert-tiny2
  - optimizer: adam
  - trainer: ${model}-${dataset}

project_name: "bert-russian-sentiment-emotion"

log_wandb: False

task: eval
# task: train
